name: ci

on: pull_request

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: myimage:latest
          load: true

      - name: Scan image
        id: scan
        uses: anchore/scan-action@v2
        with:
          image: myimage:latest
          acs-report-enable: true

      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
